package de.fhg.iais.kd.tm.liblda.inference.gibbs;

import java.util.Arrays;
import java.util.List;

import de.fhg.iais.kd.tm.liblda.DataReader;

public class AbstractGibbsSamplerTestFixture extends DataReader {

    protected static final List<String> TOPIC0_TOPWORDS = Arrays.asList(new String[]{"water", "co2", "hot", "use",
            "kg", "save", "year", "heater", "products", "reduce", "heating", "savings", "shower", "appliances", "make",
            "1", "lot", "electric", "tank", "install", "store", "uses", "10", "little", "it's", "instead", "turn",
            "need", "designed", "insulate", "old", "clothes", "flow", "easy", "add", "sure", "average", "person",
            "replace", "low-flow", "features", "standard", "don't", "bulbs", "reuse", "buying", "heads", "best",
            "pipes", "4", "6", "things", "litres", "money", "big", "50", "pipe", "run", "dryer", "tips", "20", "half",
            "heaters", "going", "power", "saves", "course", "tons", "leave", "saving", "help", "dry", "items",
            "washer", "head", "having", "hardware", "aerators", "prevent", "friends", "mower", "double", "purchased",
            "faucet", "end", "dont", "thermostats", "included", "spray", "easier", "inexpensive", "refrigerator",
            "mainly", "metric", "you're", "washing", "regular", "dishwasher", "11", "switch", "drain", "households",
            "leaky", "tell", "access", "kitchen", "tanks", "pool", "lawn", "significant", "000", "strip", "avoid",
            "switching", "mail", "toilet", "metres", "contractor", "repair", "conservation", "lost", "faucets", "tap",
            "fit", "informed", "devices", "22", "vary", "fridge", "26", "adjust", "454", "136", "phone", "wash",
            "goes", "16", "cleaning", "eat", "minute", "adds", "junk", "push", "contributes", "communities",
            "purchase", "properly", "morning", "sizes", "soft", "shows", "producing", "sink", "condensing",
            "neighbour", "steady", "computers", "45", "can't", "unplug", "567", "special", "tumble", "318", "(75)",
            "tree", "268", "fluorescent", "purchasing", "rubbish", "contribution", "showers", "19", "uv", "categories",
            "wasted", "send", "distribute", "chimney", "downhill", "core", "basements", "runs", "bit", "wrap",
            "unsure", "that's", "upstairs", "bought", "dishwashers", "dishes", "80%", "words", "compensate", "no-voc",
            "fumes", "180", "improved", "severe", "idle", "article", "40", "decrease", "scalding", "60c", "plugged",
            "228", "forego", "635", "hit", "coils", "clear", "planting", "conditioning", "alternately", "harder",
            "incandescent", "bulb", "(30)", "18", "14", "bins", "91", "12", "317", "(18)", "diet", "meat", "poultry",
            "430", "glazed", "536", "jacket", "eliminate", "basket", "lowers", "johns", "pretty", "shake", "sheathed",
            "exist", "showed", "blankets", "contact", "extreme", "leader", "#1", "#4", "mix", "debris", "storing",
            "man-made", "amazon", "contrast", "secure", "tape", "jackets", "vents", "pulsing", "wear", "parking",
            "bedrooms", "icio", "kuczia", "opens", "vistas", "covering", "lo-tech", "retrofit", "ecocel", "turpentine",
            "pastel", "colours", "accounted", "cold)", "c02", "thats", "810", "balloons", "discussion", "temptation",
            "outlined", "ado", "120f)", "burns", "617", "shut", "charger", "coffee", "pot", "tv", "unplugging",
            "greasy", "promise", "worst", "offenders", "clothing", "55", "year-round", "bump", "worst-offender",
            "defrost", "attractive", "go-getter", "cast", "one-half", "907", "72", "wearing", "181", "1167", "socket",
            "lots", "takeout", "reusable", "sponges", "craigslist", "grocery", "2/3", "showerheads", "tempest", "(50)",
            "190", "485", "vegetarian", "flatulence", "eggs", "meals", "215", "mailbox", "co2-emitting", "405",
            "million)", "17", "hate", "mornings", "mow", "exercise", "reel", "gasses", "customised", "maximises",
            "employ", "whopping", "(122)", "535", "902", "(613)", "caulk", "weather-strip", "doorways", "(137)", "361",
            "cooled", "227", "conserves", "426", "five", "subsidies", "invalid", "collector", "volumetric", "managers",
            "recommendation", "home-owners", "innovation", "inter-institute", "defects", "(kitchen", "do-it-yourself",
            "begin?", "evaluate", "drafts", "containers", "mulching", "benefiting", "coolest", "shaving", "mechanisms",
            "drawn", "stone-coated", "insulationalways", "fashion", "twenty-five", "polyethylene", "attribute",
            "stays", "ir", "xps", "ratedthat", "accessible", "modulating", "pose", "denvers", "complaints", "drinking",
            "careful", "school", "frequent", "sister", "rare", "burden", "airer", "resist", "boiling", "kettle", "lag",
            "energy-consuming)", "fell", "coupled", "21st", "passing", "culprit", "warms", "03%", "60f", "chlorophyll",
            "exchanges", "air-sea", "largely", "removing", "farms", "civilized", "reinforce", "cap", "efficiencies",
            "fails", "specialist!", "intake", "blocking", "(also", "power-vented)", "super", "pushes", "minute!",
            "threads", "water!", "aerated", "maintaining", "non-aerated", "maintains", "forceful", "dripping",
            "fixing", "wrench", "suffer", "accidentally", "5c", "ranges", "dial", "vacation", "first!", "duplexes",
            "hose", "ford", "less-powered", "150", "socio-economic", "assess", "sub-divisions", "purchaser",
            "personal/neighbourhood", "un-ecological", "comparisons", "unload", "overdrive", "pillar", "85%", "(ffvs)",
            "wise", "refining", "shipped", "recyclables)", "products)", "emissions)", "--", "blamed", "senior", "path",
            "emitters", "time'", "'builders", "struggling", "stand-by", "recruiting", "waves", "1994", "lintels",
            "finer", "bonded", "consultants", "(esd", "wednesday", "diggdigg", "usdel", "facebookfacebook", "normal",
            "eco-life", "looked", "wandering", "reading", "house?", "(albeit", "open-plan", "work)", "theory",
            "opened", "pre-teen", "fantastic", "haven't", "collects", "worrying", "hoping", "deluge", "tetrapaks",
            "cartons", "co-op", "noticeable", "stealing", "skateboards", "busy", "punctual", "sorted", "appeared",
            "censorship", "stern", "supermarket", "forgiven", "compound", "21", "impossible", "roughly", "tub)",
            "tubs?", "apartment", "owns", "pans"});

    protected static final List<String> TOPIC1_TOPWORDS = Arrays.asList(new String[]{"emissions", "gas", "fuel",
            "greenhouse", "vehicle", "total", "car", "waste", "personal", "electricity", "number", "produce", "travel",
            "example", "5", "different", "household", "change", "2", "does", "produces", "type", "work", "recycling",
            "trips", "trip", "calculator", "gases", "affect", "produced", "distance", "gasoline", "3", "vehicles",
            "based", "taken", "average", "estimate", "cars", "1", "fewer", "people", "kilometre", "ways", "reduces",
            "emissions?", "recycle", "transportation", "business", "garbage", "paper", "economy", "local", "climate",
            "choose", "family", "mode", "changes", "recreational", "shown", "grams", "taking", "consume", "4", "week",
            "round", "screen", "category", "multiplied", "better", "list", "established", "kilometres", "litre",
            "occupancy", "landfill", "motor", "7", "remember", "amounts", "bus", "travelled", "travelling", "bags",
            "drive", "9", "automatically", "takes", "depending", "assumed", "finally", "engine", "propane",
            "appliance", "(the", "city", "needed", "divided", "factor", "rail", "modes", "containers", "probably",
            "blend", "engines", "types", "usually", "added", "consumed", "province", "substantially", "visit",
            "information", "rule", "studies", "scientific", "out-of-town", "passenger", "say", "composting", "lets",
            "school", "typically", "purposes", "consumes", "standard", "stoves", "", "hold", "provides", "mid-size",
            "fairly", "length", "chose", "aircraft", "bar", "yard", "disclaimer", "epa's", "estimated", "walking",
            "thumb", ")", "walk", "0", "smaller", "15", "twice", "dryers", "generates", "big", "public", "places",
            "estimates", "report", "asked", "questions", "larger", "conserve", "return", "enter", "calculated?",
            "share", "arrive", "electronics", "compost", "hour", "organizations", "occupant", "country", "(a",
            "biodiesel", "commuter", "passengers", "cottage", "plus", "turning", "km", "disposal", "community",
            "applies", "visits", "user", "meant", "sport-utility", "fly", "numbers", "portion", "bin", "operation",
            "trucks", "college", "(or", "convert", "break", "car's", "cubic", "dodge", "ethanol", "bike", "e85",
            "kilograms", "powerful", "friend", "riding", "tubs", "fridges", "stove", "general", "think", "regions",
            "subject", "entertainment", "counted", "in)", "definition", "mini-van", "drop", "lived", "train", "jet",
            "trains", "fraction", "fall", "cycling", "calculate", "releases", "appropriate", "metre", "mind",
            "litres/100", "earlier", "vehicle's", "kinds", "fuel-efficient", "tire", "pounds", "commuting", "driven",
            "bicycle", "transit", "subways", "recreation", "boat", "camper", "screens", "boats", "worth", "developers",
            "percentage", "cook", "gaining", "individuals", "it?", "throwing", "rush", "500", "smog", "(less",
            "received", "28%", "travel?", "distance?", "notice", "car(s)", "130", "airplane", "less", "occupants",
            "buses", "repeated", "tuned", "sized", "goods", "grass", "epas", "river", "mention", "assumes", "stop",
            "batteries", "supplies", "printer", "off-set", "businesses", "work?", "modified", "educating", "converts",
            "outcomes", "subcompacts", "compacts", "mini-vans", "honda", "full-size", "pickup", "(with", "gasolines",
            "$2800", "ride", "listed", "ffvs", "curbside", "bag", "holds", "printers", "subway", "driver)", "modal",
            "slider", "corner", "outboard", "small-engine", "trailer", "snowmobile", "sea-doos", "trailers", "atvs",
            "spend", "skiing", "(3)", "adhesives", "infestation", "insecticide", "certain", "50%)", "conny", "800",
            "western", "compressors", "pleasant", "the", "outdone", "mobile", "lamps", "meat-free", "update",
            "register", "fulfilments", "inclusion", "articles", "state-of-the-art", "heating/hot", "(architecture)",
            "addresses", "rear", "declared", "humanity", "smokestacks", "1900", "warming-related", "gone", "gained",
            "record", "afore", "vacations", "traveled", "149", "128", "64", "158", "230", "flew", "florida", "holiday",
            "pick", "more", "2400", "250", "showing", "markets", "(pdf", "59", "teeth", "reflected", "fertilizer",
            "exchanger", "chimney", "flashing", "(10", "existence", "romans", "internal", "client", "bronchitis",
            "drains", "sludge", "generators", "games", "check)", "climate-change", "performer", "6mb", "hand-held",
            "videos", "toolkits", "serve", "showering", "identifying", "power)", "unpleasant", "banana", "stages",
            "drag", "imitating", "predicting", "metallic", "block", "extract", "55c", "knows", "exposed", "drafty",
            "stops", "batts)", "conviction", "insulators", "30of", "danger", "important?", "practitioner", "that!",
            "daub", "drives", "geo", "metro", "tercel", "corolla", "subcompact", "camry", "mazda", "lincoln", "grand",
            "marquis", "ram", "explorer", "caravan", "cylinders", "exception", "models)", "(meaning", "gasoline)",
            "28", "modifications", "void", "converted", "dual", "system)", "switzerland", "long-lived", "risen",
            "inventories", "reviewed", "broken", "disadvantages", "'written", "self-builders", "jointly-run",
            "epa/doe", "model)", "calculator)", "meets", "brakes", "accelerations", "idling", "well-maintained",
            "safer!", "tires", "glove", "driver's-side", "carpool", "errands", "(working", "filler", "boil", "tides",
            "bay", "leftover", "britains", "alexander", "chord", "camera", "waste?", "(either", "(22", "produce?",
            "disposed", "equal", "westerner", "(trees", "crude", "iron", "landfills)", "sending", "do!", "curb", "out",
            "trimmings", "buried", "(lighting", "operating", "activate", "copiers", "star-labeled", "productive",
            "biking", "employee", "environmentally-informed", "breakthrough", "reacted", "redditreddit", "universally",
            "niggles", "100-200", "climb", "bird's", "pouring", "container", "bits", "we'd", "chat", "feuds",
            "daycare", "metropolitan", "trip)", "week!", "(city", "156", "comparable", "34", "316", "decide", "thirds",
            "jams", "friends)", "(you", "selects", "31", "bicycles", "happens!", "displays", "weekly", "kilowatt-hour",
            "recreation?", "10-", "15-horsepower", "100-horsepower", "inboard", "sea-doo", "(single-engine", "cessna",
            "172", "(motor", "home)", "(hard", "top)", "all-terrain", "cruisers", "dealers", "rvs", "pulling",
            "displayed", "activities?", "file", "kayaking", "cross-country", "hiking", "persons", "(clothes",
            "laundromat", "boosts", "jets"});
    protected static final List<String> TOPIC2_TOPWORDS = Arrays.asList(new String[]{"building", "materials",
            "sustainable", "material", "years", "roof", "available", "built", "new", "build", "need", "wood",
            "industry", "-", "lime", "development", "concrete", "including", "used", "needs", "cob", "locally",
            "recycled", "form", "product", "roofing", "cement", "expensive", "buildings", "market", "necessary",
            "moisture", "straw", "reclaimed", "thermal", "methods", "tiles", "builders", "projects", "great",
            "resource", "long", "embodied", "choice", "tonnes", "thatch", "centre", "original", "forms", "clay",
            "suppliers", "public", "able", "options", "gives", "timber", "alternative", "architects", "demand",
            "earth", "old", "basic", "shakes", "sand", "biomass", "gain", "sourced", "key", "widely", "unfortunately",
            "application", "associated", "recyclable", "creating", "british", "specific", "inches", "century", "claim",
            "huge", "traditional", "raw", "binder", "quite", "general", "direct", "sold", "state", "absorbs",
            "hundreds", "actually", "association", "thatching", "reed", "contractors", "novacem", "passive",
            "architect", "allowing", "solid", "downside", "treated", "biodegradable", "requirements", "manufactured",
            "nature", "combination", "deal", "000", "option", "start", "sustainability", "later", "dr", "america",
            "availability", "readily", "quickly", "britain", "plaster", "mixed", "mix", "wet", "demolition", "remain",
            "salvage", "value", "waiting", "rammed", "english", "shape", "ask", "various", "unnecessary", "reflect",
            "boards", "easier", "beams", "compressed", "insulator", "surfaces", "safe", "responsible", "finding",
            "drying", "membrane", "rapid", "for?", "interior", "researching", "owned", "previous", "resistant",
            "revival", "limestone", "putty", "rendering", "recently", "advantage", "classified", "specifications",
            "stones", "reclamation", "1%", "laid", "managed", "scotland", "durable", "texture", "skill", "shingles",
            "extent", "internet", "mud", "search", "quarry", "bearing", "cumbria", "roads", "magnesium", "i've",
            "ready", "environmentally-friendly", "component", "(unless", "hemp", "lightweight", "excellent",
            "allergen-free", "inevitably", "bricks", "device", "question", "filled", "advance", "lives", "intensive",
            "'green", "select", "losses", "agent", "contract", "cladding", "todays", "19th", "board", "truss", "ridge",
            "colors", "planned", "specify", "strength", "leading", "version", "power-vented", "masonry", "claimed",
            "overhang", "refined", "plasters", "historic", "fabric", "solution", "bale", "ships", "permeable",
            "mortar", "mixes", "particle", "excessive", "director", "adapted", "reprocessed", "immense",
            "deconstruction", "demolished", "untapped", "substantial", "secured", "supplying", "eco-house", "courses",
            "priority", "grasses", "thatched", "reeds", "wheat", "technique", "imported", "flammable", "heartwood",
            "bamboo", "fast", "ideally", "possibilities", "distinctive", "leaving", "600", "healthier", "aluminum",
            "sue", "wrong", "budget", "man", "wasn't", "straight", "quick", "burnt", "novacem's", "tonne", "designers",
            "drink", "streets", "charcoal", "self", "chameleon", "kuczias", "silesia", "planks", "bbq", "(pre-cut",
            "thickness", "rafter", "exceptionally", "fungicide", "quilts", "borate", "homatherm", "fired", "pellets",
            "handled", "prohibitive", "outweigh", "(vocs)", "misused", "eco-labels", "well-adjusted", "lone", "wrang",
            "children", "practically", "profitability", "passive-", "well-built", "kilowatt-hours", "excluding",
            "billion)", "dirty", "advancing", "catalyzing", "columbia's", "fee-based", "first-stop", "deeper",
            "assistance", "consulting", "accelerate", "columbia", "representatives", "guests", "invited",
            "well-researched", "classification", "feet", "low-lying", "sheds", "mimic", "waterproof", "index",
            "fibrous", "membranes)", "flooding", "guidance", "marketed", "guidelines", "genuinely", "epcs", "radical",
            "bathwater", "consequently", "guillermo", "riffat", "showpiece", "in!", "municipal", "packing",
            "nutrients", "enable", "substitution", "25th", "they?", "foil", "4s", "master", "bright", "craw",
            "now-banned", "flanges", "perforated", "renewed", "envelope", "warmest", "recessed-can", "rater",
            "demand-side", "convinced", "depressurizing", "lines", "restrictors", "encountered", "sparks", "landing",
            "changed!", "transmittance", "guessed", "flashing!", "werent", "centennial", "archaeological",
            "durability", "qualities", "extensively", "programme", "principal", "nineteenth", "cements", "function",
            "understanding", "ecologically-minded", "renovation", "undergoing", "gypsum", "suited", "coat",
            "re-worked", "follows", "pointing", "plastering", "diluted", "recommends", "cement-free", "prickly",
            "(nopal)", "ancient", "workable", "adhere", "thinners", "annoying", "sleep", "loaded", "powders", "tanks",
            "converters", "energy-producing", "ellen", "copy", "previously", "refinished", "stairs", "cobbled",
            "re-purposing", "reclaim?", "massive", "122", "(1/3", "re-modelling", "salvaged", "heritage", "gleamed",
            "equipped", "orders", "redirecting", "stream", "atmosphere)", "whole-house", "floor)", "coil",
            "south-facing", "3%", "9%", "leveland", "wishing", "clay-based", "expectation", "sustainablebuild",
            "uk/strawbale", "yurts", "merge", "varied", "re-use", "lightbulbs", "lead-free", "bedzed", "borough",
            "sutton", "peabody", "recognising", "plays", "complex", "oldest", "coconut", "caribbean", "leaves",
            "predominant", "cottages", "oats", "broom", "bracken", "threshed", "ears", "shaggy", "lifespan",
            "thatcher", "bundles", "pegged", "rods", "successive", "ridgeline", "rains", "restrictions", "medieval",
            "traditionally", "hand-splitting", "logs", "shaped", "rustic", "smoother", "unseasoned", "hardwood",
            "straight-grained", "decaying", "overlapping", "vegetative", "sustainable?", "recognised", "96",
            "widening", "efforts", "judge", "environment?", "happy", "communicate", "advise", "entitled", "certified",
            "recyclable!", "somerset", "basins", "you!", "beach", "driftwood", "practitioners", "enjoy!", "immensely",
            "ingenuity", "creativity", "vehicale", "system", "translated", "perfluorocarbons", "regime",
            "inappropriate", "alike", "library", "timeless", "dressed", "emulates", "stone-built", "responding",
            "prevailing", "adaptations", "happening", "markings", "dated", "enthusiastic", "physically", "demanding",
            "accent", "rack", "mileage", "under-inflation", "energys", "composite", "timbers", "syndrome", "desirable",
            "formations", "baking", "hotel", "jeff", "aim-listed", "foremost", "decomposes", "fringe", "family-safe",
            "builds", "worry", "advent", "defra", "bolted", "enshrined", "human)", "agrees", "handy", "accidental",
            "airtightness", "140", "(ensuring", "-as", "southwest", "dying", "mccabe", "70", "storeys", "small)",
            "won", "award", "staggering", "(clay-based)", "mixture", "workmen", "150mm", "450", "dried", "trimmed",
            "men", "treading", "stronger", "(generally", "embed", "300mm", "mm", "rubble", "bare", "rendered",
            "render", "coarse", "granite", "footings", "london-based", "sulphate", "consequences", "announcement",
            "tested", "eagerly", "unplugged", "newsvinenewsvine", "journalist", "story", "remarked", "reasonable",
            "start-up", "squared", "tried", "nasty", "hazard", "weeding", "dodgy", "cosy", "recycles", "terribly",
            "sticks", "whizzing", "friendliness", "bitter", "era", "rv", "tests"});
    protected static final List<String> TOPIC3_TOPWORDS = Arrays.asList(new String[]{"carbon", "greenhouse",
            "emissions", "reduce", "climate", "atmosphere", "dioxide", "change", "effect", "fuels", "fossil", "gases",
            "global", "warming", "activities", "world", "students", "human", "power", "increase", "school", "process",
            "burning", "earth", "ways", "way", "methane", "footprint", "light", "generate", "industrial", "ozone",
            "earth's", "scientists", "developing", "various", "life", "burn", "schools", "infrared", "manufacturing",
            "cycle", "(co2)", "trees", "absorb", "emission", "nations", "release", "impacts", "coal", "science",
            "offer", "overall", "learn", "production", "rate", "planet", "action", "helps", "emitted", "offset",
            "released", "programs", "5%", "forests", "amounts", "stored", "pollutants", "measures", "individual",
            "reductions", "role", "concentration", "investigate", "exit", "epa", "actions", "revolution", "causes",
            "parts", "millions", "mmtc)", "simulation", "co2", "upper", "force", "binding", "nitrous", "oxide",
            "electronic", "involves", "develop", "evidence", "trend", "activity", "driving", "reach", "economies",
            "centuries", "choices", "occurring", "(figure", "chlorofluorocarbons", "ecosystem", "visible",
            "manufacture", "promoting", "strong", "matter", "educators", "school's", "ratio", "from?", "figures",
            "continue", "emit", "leads", "6", "planting", "gets", "plants", "depletion", "scientific", "sea",
            "program", "reusing", "phenomenon", "agricultural", "phenomena", "ultraviolet", "eventually", "forest",
            "biological", "formed", "steam", "administrators", "inventory", "classroom", "schemes", "caused",
            "'carbon", "respiration", "photosynthesis", "operates", "sun", "alternatives", "regulation", "contributor",
            "thought", "western", "treaty", "december", "critical", "agriculture", "explore", "dead", "offering",
            "sunlight", "accelerating", "reaches", "influence", "equivalent", "newspapers", "beverage", "spread",
            "causing", "(o3)", "(cfcs)", "nitrogen", "defined", "instance", "animals", "vast", "quantities",
            "deposits", "hydrocarbons", "(ch4)", "greatest", "cfcs", "industries", "combine", "turns", "wheel", "card",
            "links", "citizens", "output", "offsetting", "initiative", "policy", "employees", "dependence",
            "sequestration", "supporting", "carbohydrates", "simulations", "minimize", "agree", "occurs", "negotiated",
            "russia", "extremely", "hang", "achieve", "aside", "very", "intergovernmental", "word", "fahrenheit",
            "debate", "modify", "pdf)", "landfills", "200", "capacity", "maintained", "concentrated", "captured",
            "patterns", "ecosystems", "destroy", "glossary", "comprises", "(0", "supports", "biotic", "abiotic",
            "engage", "gradients", "spectrum", "wavelengths", "radiant", "exposure", "crust", "atomic", "faster",
            "(n2o)", "accumulated", "deforestation", "sprays", "blowing", "montreal", "schedule", "18th", "manual",
            "transition", "culture", "edge", "crucial", "happens", "bring", "lungs", "destroys", "machinery",
            "mitigate", "bodies", "play", "kit", "submit", "universities", "campus", "informal", "middle", "clicking",
            "successful", "two-sided", "printing", "copying", "cartridges", "leasing", "donate", "implementing",
            "continues", "hugely", "68f", "seek", "'offsetting'", "actively", "institutions", "'annex", "i'",
            "credits'", "workplace", "enacting", "dwelling", "eco-construction", "input", "oceans", "creatures",
            "shells", "boundary", "atmospheric", "importance", "soils", "decay", "world's", "growth", "conserving",
            "everytime", "stores", "alters", "threat", "post-2000", "anthropogenic", "interference", "arresting",
            "simulators", "limit", "beginning", "generation", "hypotheses", "order", "retardants", "binder)", "kidney",
            "fragrance", "29%", "sulfur", "pfcs", "five-year", "permitted", "layering", "cut", "farmer's",
            "showerhead", "water?", "saturday", "(218)", "granville", "garages", "(stonecrop)", "space'", "roger",
            "applications", "feb", "studying", "mounting", "tailpipes", "raising", "momentum", "centered",
            "unprecedented", "vice", "documentary", "awarded", "oscar", "supreme", "protection", "justified",
            "authorized", "1970", "2100", "23", "experimental", "conclusions", "mb", "efficiently", "irrigating",
            "flush", "analogous", "15oc", "greatly", "accelerated", "pace", "4)", "polar", "productivity", "claiming",
            "2°c", "eventuates", "self-reinforcing", "molecule", "obliged", "recover", "antarctic", "5)", "depletions",
            "arctic", "arranged", "composed", "08%)", "93%)", "oscillations", "referent", "watershed", "coastal",
            "characteristic", "flora", "fauna", "addressed", "tern", "relationships", "webs", "43%", "capable",
            "stable", "sunburn", "cancers", "49", "lie", "transparent", "fossilized", "bonds", "2006", "primary",
            "non-renewable", "termed", "exploration", "tropospheric", "human-produced", "aerosol", "foams", "cfc",
            "trap", "halocarbons", "profound", "socioeconomic", "globe", "shift", "labor", "machine-based",
            "mechanization", "textile", "fuelled", "sharp", "hydrophonics", "extremes", "wind-turbine", "accept",
            "trusses", "no-added-formaldehyde", "1991", "r-13", "originally", "furnace-water", "u-factor", "adventure",
            "resilience", "pear", "caustic", "silica)", "illness", "exhausts", "noxious", "silt-bearing",
            "assessments", "dampen", "watch", "animations", "teachers", "everyday", "(climate", "excel", "spreadsheet",
            "mb)", "conceptualize", "drivers", "dorm", "teach", "wildlands", "habitats", "download", "eight-page",
            "brochure", "(8", "illustrated", "estimating", "thinking", "introducing", "contributions", "educator",
            "audiences", "searchable", "database", "books", "performers", "partnering", "k-12", "track", "districts",
            "leaders", "ceramic", "hear", "gadgets", "hall", "protective", "suggestions", "jug", "off-setting",
            "welcomed", "apparent", "sustaining", "footprint'", "necessarily", "(their", "footprint)", "offsetting'",
            "obligated", "bound", "comply", "(industrialised", "carbon)", "dictate", "enabling", "overstepping",
            "limitations", "stands", "obligation", "encouraging", "arguably", "merely", "continuing", "(such",
            "village", "utilises", "knowing", "radically", "unnatural", "exhales", "bloodstream", "biochemical",
            "closely", "dissolves", "algae", "sea-dwelling", "eaten", "die", "ocean", "latecomer", "locked", "31%",
            "(293", "diesel/heating", "1480", "(146", "tiny", "quantify", "eating", "co2-removing", "(wheat", "snow",
            "mainstream", "artificially", "rice", "paddies", "sophisticated", "attempt", "predict", "(measured",
            "dioxide)", "approximation", "proportion", "argue", "catalyze", "face", "enjoy", "tissues", "intricate",
            "fluxes", "consequence", "technologically", "directed", "income", "kinetic", "refers", "mileage)",
            "liters", "recognizing", "usefulness", "flight", "circuit", "mathematical", "infinite", "$2000",
            "framework", "session", "east", "zealand", "(n20)", "(hfcs)", "(pfcs)", "1995", "deplete", "members)",
            "financing", "protocol-related", "observers", "on-going", "(cop/mop-3)", "]", "cellular", "lucky",
            "scores", "customized", "cleanest", "internet)", "sticker", "urgent", "rapidly", "scarce", "inputs",
            "mites", "eczema", "palpitations", "recognise", "pipeline", "tar", "proposal", "funding", "happened",
            "leds", "manipulate", "tourists", "google", "containers)", "standard-sized", "puts", "breaks",
            "landfilled", "change)", "tacking", "compromised", "manage", "earned", "insist", "guilty", "stating",
            "confident", "respected", "party", "implemented", "odometer", "pools", "cools"});
    protected static final List<String> TOPIC4_TOPWORDS = Arrays.asList(new String[]{"use", "used", "natural",
            "using", "reducing", "low", "environment", "oil", "make", "help", "include", "stone", "paints", "small",
            "impact", "look", "live", "create", "possible", "large", "people", "modern", "known", "source", "come",
            "brick", "paint", "companies", "potential", "conventional", "main", "making", "hand", "diesel", "process",
            "given", "terms", "easily", "examples", "called", "layer", "includes", "organic", "makes", "size",
            "quality", "order", "right", "contain", "chemical", "currently", "major", "damage", "worldwide", "burned",
            "heavy", "comes", "power", "standards", "countries", "said", "away", "pressure", "current", "high",
            "created", "generated", "cause", "risk", "combined", "solvents", "highly", "relatively", "considered",
            "turbine", "structures", "breathe", "forced", "indicate", "biggest", "operate", "feature", "effective",
            "weight", "naturally", "petroleum", "rolls", "cheaper", "flax", "100", "rising", "vocs", "voc",
            "essential", "unlike", "refrigerators", "rise", "involved", "seen", "underground", "co2-friendly",
            "portfolio", "investing", "loose", "mineral", "contains", "eye", "labels", "colour", "obvious", "invest",
            "emission", "consists", "sun's", "involve", "trade", "bigger", "separated", "plastics", "allowed",
            "clearly", "requires", "35", "considerable", "effectively", "truck", "refinery", "linked", "varies",
            "wool", "ability", "advantages", "ingredients", "compounds", "concerns", "decisions", "minimal", "tend",
            "composted", "generations", "region", "age", "nuclear", "offset", "regional", "affecting", "calculating",
            "cases", "stations", "history", "external", "considering", "breathable", "calcium", "trust", "(which",
            "opposed", "traps", "literally", "councils", "pumped", "advanced", "trapped", "converting", "lighter",
            "heavier", "transported", "road", "dams", "grades", "tanker", "traffic", "(watt)", "context", "stud",
            "petrochemicals", "additives", "forestry", "aggregate", "pigment", "binders", "headaches", "fatigue",
            "skin", "cancer", "low-voc", "direction", "milk", "(distilled", "solvent", "chemically", "changing", "24",
            "committed", "exactly", "concerned", "surroundings", "mr", "udby", "lies", "demands", "red", "mowers",
            "retention", "criteria", "delivered", "staff", "irreversible", "abundance", "distribution", "(low-e",
            "liquid", "carbonate", "trapping", "diameter", "dispose", "rooms", "enhance", "referred", "believe",
            "temporarily", "(for", "megajoules", "routine", "law", "legal", "creates", "climates", "bales", "abundant",
            "flows", "winds", "moves", "adverse", "dangerous", "rates", "hints", "certification", "shops", "pots",
            "guides", "covers", "quarried", "signs", "quarrying", "slow", "designing", "reasons", "adopt", "funnelled",
            "hydro-electric", "rivers", "elevation", "dam", "generating", "generator", "butane", "kerosene",
            "reservoirs", "turpin-brooks", "won't", "ash", "object", "(7)", "supply)", "teacher", "inside", "vegan",
            "unwanted", "multi-foils", "assumption", "imported)", "retardant", "newsprint", "additive", "by-products",
            "thermowall", "expand", "weight-bearing", "(disperses", "chromium", "benzene", "formaldehyde", "driers",
            "based)", "evaporate", "numerous", "nausea", "disorders", "fungicides", "odourless", "odour-free",
            "defining", "logos", "eco-label", "usa", "classifications", "(0-0", "petrochemical", "questionable",
            "dyes", "minerals", "linseed", "(from", "seeds)", "protein", "authentic", "restoration", "chalk",
            "thicken", "pine", "fruits", "colorants", "sufferers", "unable", "tolerate", "micro-porous", "prone",
            "flaking", "(sometimes", "more)", "safe", "protecting", "children", "energi", "ready-built", "ceo",
            "division", "sacrifices", "players", "visualize", "responsible", "m2", "wishes", "shrubs", "survive",
            "visiting", "representative", "inception", "landlord/owner", "stimulate", "(iset)", "poverty", "security",
            "competitiveness", "gore's", "expertise", "year!", "occupancies", "wasters", "label", "one-third", "-18°c",
            "feedback", "agreements", "absorbing", "band", "molecules", "cumulative", "fertilizers", "refrigerants",
            "exerted", "peat", "spring", "reverse", "tomatoes", "(osb)", "cotton", "width", "coefficient",
            "ownershipits", "squeezed", "acceptable", "heating-related", "circulating", "on", "mortars",
            "anti-bacterial", "ultra-violet", "brands", "quicklime", "gel", "primed", "soot", "vapours", "sediment",
            "drinks", "hearing", "usable", "nationwide", "earn", "toolkit", "formal", "2008-2009", "kroner", "altered",
            "dismantle", "specialist", "high-end", "chain", "enormous", "par", "energy-intensive", "conjunction",
            "midefficiency", "poorer", "6c)", "164", "signatories", "signatory", "scheme", "non-harmful",
            "refinements", "page", "gers", "nomadic", "decompose", "(like", "sustainably", "capital", "machynlleth",
            "internationally-agreed", "elaborate", "appreciates", "breathes", "drift", "hum", "civilization", "280",
            "367", "(533", "(219", "outwards", "withstand", "attributable", "involving", "accurately", "protocol's",
            "endorsing", "supporters", "critics", "climate!", "capita", "analogue", "concentrate", "higher-efficiency",
            "prematurely", "styrofoam", "alloys", "foreseeable", "dealing", "clients", "specifies", "creative",
            "golden", "oldies", "straw)", "civic", "neon", "accord", "626", "falling", "renters", "desirability",
            "installation", "elegance", "weighing", "straight-forward", "anchoring", "restored", "involvement",
            "ireland", "laborious", "patience", "nation's", "b5", "dependent", "accounting", "survival", "symptoms",
            "electricty", "pressurized", "reservoir", "falls", "funneled", "diesel-powered", "hydroelectricity",
            "fast-moving", "naphtha", "distilled", "breakdown", "geologic", "refined)", "progressively", "marine",
            "bunker", "c", "asphalt", "residue", "unusable", "flared", "drums", "depots", "making/repair", "ordered",
            "chief", "extend", "ore", "proofing", "motivation", "'water", "46", "aecb)", "lecturer", "economy?'",
            "developer/builders", "tends", "cheaply", "longwood", "german", "membership-based", "would-be", "creation",
            "carpooling", "745", "500mm", "100mm", "(3-5%", "damp)", "potentially", "manipulated", "destruction",
            "trial", "operations", "initiated", "watery", "vechicle", "disseminate", "internationally", "rural",
            "deprived", "dreams", "realised", "stumble", "text", "photos", "developer", "pointed",
            "electricity-generating", "scrub", "sky", "respect", "bygone", "bunch", "draught-proofing", "trains)",
            "scroll", "canoeing", "finite", "washers", "dishwashing", "heat-dry"});
    protected static final List<String> TOPIC5_TOPWORDS = Arrays.asList(new String[]{"energy", "home", "house",
            "project", "epc", "property", "efficiency", "performance", "-", "housing", "renewable", "solar",
            "buildings", "cost", "information", "heating", "future", "commercial", "efficient", "guide", "simple",
            "certificate", "homes", "addition", "required", "panels", "consider", "improve", "lighting", "require",
            "domestic", "factors", "supply", "check", "local", "2008", "responsible", "research", "issue", "wind",
            "production", "let", "consumer", "level", "certificates", "heat", "properties", "neutral", "landlord",
            "qualified", "rented", "star", "concept", "web", "near", "sources", "constructed", "services", "sector",
            "private", "ensure", "assessment", "case", "'", "following", "sib", "island", "social", "details", "sell",
            "independent", "assessor", "typical", "controls", "useful", "present", "cavity", "want", "saving",
            "providers", "residential", "&", "rent", "valid", "provided", "rating", "ratings", "prospective", "steps",
            "chris", "opportunity", "affected", "comfortable", "turned", "behaviour", "owners", "regarding",
            "planning", "free", "short", "october", "lettings", "seller", "improvements", "e", "premises", "turbines",
            "smart", "monitor", "real", "expert", "inhabitants", "reduces", "existing", "prices", "frequently",
            "denmark", "zero+", "ordinary", "especially", "manager", "facts", "carry", "miles", "buyers", "sale",
            "conduct", "detailed", "pack", "applied", "remains", "refer", "tenant", "buyer", "loft", "boiler",
            "approach", "open", "poor", "hole", "carbon-neutral", "initial", "sense", "doesn't", "running",
            "completed", "house's", "g", "landscape", "intelligent", "price", "denmark's", "so-called",
            "grontmij|carl", "bro", "interested", "annual", "unique", "recommendations", "300", "display",
            "inspiration", "blanket", "advice", "rental", "provider", "inspector", "landlords", "accommodation",
            "affects", "method", "adopted", "data", "recent", "instruct", "estate", "date", "improving", "aims",
            "2001", "m", "forward", "hoped", "(e", "structure", "walls)", "+low", "sonderborg", "showcase",
            "participating", "byggeri", "supplier", "syd", "dedicated", "society", "surplus", "connected", "mains",
            "department", "christian", "profitable", "correct", "wants", "energy-", "economically", "lowest",
            "architecture", "million", "focuses", "hanging", "sales", "non-profit", "incentives", "hips", "quotes",
            "sellers", "rsl's", "packs", "(hip)", "quote", "directory", "dwellings", "hip", "survey", "relevant",
            "associations", "relating", "compiled", "accredited", "licensed", "listing", "condition", "efficient)",
            "validity", "obtained", "homeowner", "view", "online", "tenants", "mandatory", "legislation", "ensuring",
            "charge", "earliest", "written", "response", "occur", "unlikely", "renting", "april", "rating?",
            "cylinder", "phd", "2050", "facade", "greener", "pp", "watersense", "hard", "educate", "crawl", "website",
            "basics", "money!", "saw", "aarhus", "acting", "london", "robust", "conceive", "machine", "27",
            "telecommuting", "containing", "northerly", "financially", "media", "marketability", "herring",
            "conscious", "they're", "getting", "sq", "dream", "overlooked", "shared", "scy-lab", "objects", "points",
            "(1)", "annotated", "screenshots", "(6)", "burgers", "mite", "thermafleece", "brand", "safely",
            "symbolically", "prins", "henriks", "avenue", "mrs", "midtgaard", "tom", "toft", "keywords", "danfoss",
            "responsibility", "connection", "torben", "golles", "speak", "backwards", "stjernholm", "saying",
            "inhabitants'", "inhabitant", "families", "versus", "self-sufficient", "repeatedly", "brings", "+house",
            "cooperation", "combining", "fulfils", "citizen's", "217", "188", "joins", "907", "delta", "fish",
            "outreach", "commitment", "cluster", "ps", "relax", "eco-roofs", "cloth", "impregnated", "wildflower",
            "butterflies", "quotation", "competitive", "(home", "pack)", "dea", "(domestic", "assessor)", "(hi)",
            "registered", "landlord's", "dec", "(epc)", "inspection", "surveys", "(energy", "certificate)",
            "undertaken", "sliding", "f", "highest", "(i", "simplify", "scales", "freezers", "etc)", "assessment?",
            "collectors", "guidelines", "clg", "(communities", "government)", "met", "collector", "authorised",
            "calculation", "(lofts", "adjacent", "noted", "software", "behalf", "compile", "documentation", "belongs",
            "'s", "rents", "voluntarily", "suggest", "approx", "obtaining", "owner", "request", "viewing", "conducted",
            "entering", "believes", "sufficient", "funds", "faqs", "student", "occupation", "certainly", ">",
            "10000m2", "exempt", "exemptions", "sap", "payback", "users", "read", "boilers", "basf", "projection",
            "leadership", "functionality", "orientated", "longest", "priorities", "quantity", "smartly",
            "unconditioned", "over-all", "greenscapes", "zone", "beneath", "reserves", "mining", "crop", "celebrated",
            "2-inch-diameter", "kindling", "agentwith", "r-21", "broke", "46)", "plane", "constant", "aggravation",
            "sideways", "hes", "(dpm)", "settlement", "district", "qualifies", "colleges", "(pdf)", "answers", "field",
            "officials", "peek", "suburb", "lystrup", "hopes", "hopefully", "ambassador", "package", "tax", "nation",
            "jespersen", "vkr", "holding", "crisis", "junkyards", "albert", "acquisition", "revealed", "wisely",
            "beneficial", "canvas", "locally-grown", "cambridgeshire", "march", "wales", "fastened", "spanish-style",
            "row", "airplanes", "ratifying", "spoiling", "stake", "resistance", "vertically", "starts", "honeycomb",
            "tightness", "85", "come?", "replenishable?", "refurbishing", "greenest!", "rarely", "chevrolet",
            "hungary", "[see", "sensible", "guide?", "renter", "examines", "arising", "fourth", "disability",
            "hazards", "stone'", "spent", "trunk", "tune", "compartment", "fueled", "soaring", "depression", "vibrant",
            "house'", "background", "sail", "bread", "badly", "opted", "off-the-shelf", "executive", "suggested",
            "remotely", "telephone", "seeking", "sponsorship", "sponsors", "leakage", "gold", "helping", "attracting",
            "giving", "msc", "eliminated", "hippy", "seriously", "proposed", "enjoying", "gas'", "chair", "56",
            "site's", "'all", "location", "'people", "june", "graded", "scratch", "insists", "'there", "more?",
            "hampered", "non-existent", "'you", "1990s", "huddersfield", "'when", "lifetime", "'the", "95", "maximize",
            "a++", "pvc", "cords", "routers", "environments", "operational", "employer", "byproducts", "objectives",
            "contruct", "staying", "attract", "remote", "grids", "agendas", "eco-development", "eco-build", "stunning",
            "fuchsia-pink", "under-floor", "triple", "wouldn't", "rid", "sit-ups", "stare", "ride!", "cruiser",
            "persons)", "reheated"});
    protected static final List<String> TOPIC6_TOPWORDS = Arrays.asList(new String[]{"just", "today", "countries",
            "costs", "protocol", "year", "light", "developed", "kyoto", "plant", "food", "technologies", "like", "cut",
            "1983", "says", "systems", "buy", "period", "life", "2", "million", "compared", "target", "trees", "-",
            "room", "zero", "achieved", "1990", "targets", "extra", "economic", "market", "european", "management",
            "national", "10%", "group", "promote", "s", "changed", "states", "company", "united", "legally", "you'll",
            "fact", "grown", "think", "ones", "model", "international", "wooden", "parties", "central", "cuts",
            "certain", "challenge", "represents", "account", "manufacturers", "ago", "3", "emits", "stay", "garden",
            "bath", "remove", "conditions", "worked", "member", "cent", "far", "active", "act", "basis",
            "industrialized", "8%", "animal", "simply", "practice", "thing", "cutting", "service", "education",
            "initiatives", "technical", "kind", "regularly", "started", "late", "doing", "moved", "conference",
            "hansen", "unst", "got", "plans", "packaging", "agreed", "carrying", "japan", "2010", "billion",
            "practical", "fix", "additional", "compact", "financial", "facilitate", "processes", "60%", "glazing",
            "combustion", "2007", "variety", "learned", "net", "difficult", "velfac", "models", "hope", "reactions",
            "demonstration", "left", "convention", "meeting", "copper", "saver", "poland", "synthetic", "marketing",
            "effects", "1997", "came", "2005", "collective", "union", "6%", "humans", "110", "oxygen", "step",
            "station", "36", "updated", "implementation", "park", "storage", "president", "truth", "nylon",
            "hydroponic", "aesthetically", "didnt", "oak", "managing", "reliable", "rain", "phase", "velux", "team",
            "mcculley", "achieves", "largest", "credits", "actual", "ecologically", "cells", "split", "sinks",
            "reversing", "eu", "meet", "projected", "commitments", "kenna", "micro", "minimised", "street", "nice",
            "volatile", "february", "agreement", "note", "hexafluoride", "7%", "australia", "iceland", "utility",
            "680", "44", "159", "transporting", "104", "petrol", "establish", "fund", "20%", "mark", "incorporated",
            "played", "heat-trapping", "calls", "federal", "20th", "1750", "u", "familiar", "1987", "subsequently",
            "high-tech", "crops", "means", "fragile", "supposed", "covenants", "restricted", "pleasing", "fires",
            "fireplace", "isnt", "osb", "inch", "manufacturer", "wetter", "im", "handle", "unit", "supplied", "rated",
            "'home", "life'", "visitors", "gave", "obama", "congress", "achieving", "aspect", "speech", "75",
            "engineers", "don", "t", "royal", "simulated", "institution", "annex", "rewarding", "mmtc", "africa",
            "observed", "attention", "profile", "ratified", "2002", "upward", "commit", "country's", "2008-2012",
            "sounds", "toyota", "2000", "mechanism", "sectors", "cooperate", "meetings", "talks", "batavia", "decided",
            "normally", "stuff", "oregon", "lay", "pump", "battery", "partners", "flowers", "depot", "communal",
            "other's", "graphs", "conceptualizations", "lakeside", "piotr", "utilizes", "faade", "sheep's",
            "regulating", "non", "(colour)", "carriers", "irritation", "angel", "29%)", "allergens", "blistering",
            "shades", "declare", "kragh", "energi's", "16th", "cut)", "goal", "hfcs", "0%", "emmisions", "hot?",
            "shouldn't", "49c", "(20)", "times?", "hair", "(128)", "detergents", "55", "clutter", "shade",
            "house-warming", "(11)", "towels", "book", "exchange", "unprocessed", "travels", "13", "73", "(275",
            "sick", "lawn?", "scotts", "321", "updating", "energy-friendly", "33", "welcome", "foot", "columbians",
            "transformation", "discuss", "evolved", "outhouses", "endangered", "insect", "met", "stimulated", "bonus",
            "layout", "57%", "saffa", "undergraduate", "undertake", "2050", "prefabrication", "red-carpet", "an",
            "ruling", "position", "radiating", "clippings", "perform", "counterparts", "brushing", "day?", "nowadays",
            "melting", "near-visible", "86%", "amendment", "railways", "erected", "opposite", "subsidized", "1983one",
            "published", "issuewas", "1970s", "foil-faced", "told", "sensed", "posed", "grandparents", "1917)", "fine",
            "unfaced", "open-cell", "infiltration", "diffusion", "experts", "commented", "visited", "bowing",
            "penetrations", "checked", "switched", "flickered", "97%", "value-engineered", "aquastar", "thanked",
            "gravity", "replacements", "puddle", "shelter", "today?", "smith", "platform", "colorado", "finish",
            "solution", "carries", "firm", "(winzip", "debut", "rhus", "receives", "embassy", "paving", "terence",
            "passed", "stimulus", "incentive", "marketable", "impressed", "modernise", "strive", "arhus", "d",
            "multidisciplinary", "fields", "philosophers", "trades", "finn", "crucially", "recuperate", "term",
            "35-40", "inspire", "kick", "officially", "humble", "statistics", "dining", "(about", "mixed)", "presided",
            "phased", "two-tier", "allocated", "car-sharing", "industrialised", "technological", "www", "82",
            "microbes", "digest", "roots", "metabolized", "sediments", "believed", "yielding", "dug", "(mmtc)", "(627",
            "utilities", "036", "slash-and-burn", "dating", "hallmark", "butt", "labour", "circulate",
            "representation", "preserve", "emissions'", "(range", "(gasoline", "body", "rolling", "simulate",
            "equations", "wasteful", "pavilions", "floorboards", "wattle", "malibu", "strengthens", "(cop3)",
            "(developed)", "closer", "convention's", "[man-made]", "distributing", "states)", "ukraine", "stabilize",
            "norway", "equivalents", "demonstrable", "�", "exceptions", "transition)", "hydrofluorocarbons", "(sf6)",
            "dealt", "richest", "(oecd", "succeed", "non-binding", "returning", "experienced", "falling",
            "emissions-control", "acquire", "joint", "enables", "finance", "emissions-reduction", "receive", "credit",
            "pursue", "encourages", "reform", "fiscal", "imperfections", "adaptation", "programmes", "reiterates",
            "incurred", "(cop)", "serves", "(mop)", "participate", "post-2012", "3rd", "bali", "reserve",
            "side-by-side", "pedal", "cruise", "ensures", "day)", "ovens", "1992", "damaged", "consultancies", "isle",
            "grateful", "recharge", "850", "write-up", "worlds", "(paper", "(this", "(sources", "messages",
            "conservative", "evident", "impartial", "'thermal", "stewardship", "kevin", "carve", "adventurous",
            "u-values", "licences", "awaited", "placements", "film", "air-to-water", "contruction", "highlands",
            "islands", "domestic/light", "o'connell", "she'd", "'living'", "farkfark", "minds", "pictures",
            "campaigned", "wistfully", "people's", "carbon-zero", "storage)", "gable", "(admittedly", "pink",
            "sleeping", "thieves", "tiled", "mould", "reluctant", "stray", "tells", "pronto", "disaster", "sunken",
            "wild", "wielding", "west", "guess", "discussing", "we're", "hop", "one-tenth", "chained", "259", "460"});
    protected static final List<String> TOPIC7_TOPWORDS = Arrays.asList(new String[]{"insulation", "air", "home",
            "heat", "windows", "walls", "house", "wall", "new", "homes", "percent", "window", "good", "doors",
            "greenhouse", "way", "reduce", "cold", "warm", "basement", "inside", "types", "better", "space", "frame",
            "foam", "glass", "usually", "efficient", "outside", "cool", "common", "foundation", "lights", "leaks",
            "furnaces", "added", "installed", "allow", "gas", "attic", "ducts", "furnace", "exterior", "know",
            "winter", "efficiency", "insulating", "months", "tip", "generally", "insulated", "increases", "plastic",
            "bills", "higher", "greater", "comfortable", "seal", "builder", "single", "fiberglass", "low-e", "close",
            "keeping", "energy-efficient", "needed", "try", "warmer", "vapor", "door", "older", "caulking", "sun",
            "batts", "r-value", "preventing", "come", "past", "6", "ceiling", "coating", "pane", "home's", "coming",
            "newer", "idea", "sealed", "allows", "feel", "heating", "tankless", "degree", "steel", "panel", "sealing",
            "weather", "job", "sheathing", "cedar", "replaced", "25", "polyiso", "barriers", "flexible", "gap",
            "cost-effective", "polystyrene", "cellulose", "provide", "loss", "minimum", "approximately", "metal",
            "duct", "contained", "sections", "polyurethane", "significantly", "30", "shopping", "heated", "adding",
            "argon", "1983", "x", "wasnt", "wider", "barrier", "frames", "cfls", "feels", "gaps", "rubber", "base",
            "floors", "keeps", "true", "style", "problem", "plugging", "celsius", "warmth", "moving", "measure", "bed",
            "took", "attics", "narrow", "denver", "wife", "exhaust", "cooler", "sprayed", "seven", "colder", "element",
            "sent", "panes", "prevents", "upgrade", "r-12", "upgrading", "weatherstripping", "openings", "outdoors",
            "load", "outer", "inner", "placed", "high-efficiency", "air/vapor", "storm", "(and", "mass", "joists",
            "fibreglass", "blown", "rot", "seals", "gains", "letting", "replacing", "60", "warmed", "mentioned",
            "installing", "escaping", "thinner", "harvested", "ive", "plywood", "bathroom", "architectural", "mounted",
            "thicker", "batt", "uninsulated", "holes", "raise", "fireplaces", "double-glazed", "touch", "r-32",
            "cracks", "apply", "analysis", "balance", "stripping", "(including", "went", "untreated", "studs",
            "success", "foundations", "sensitive", "accomplished", "favour", "blame", "foot", "easiest", "and/or",
            "inconvenient", "crawlspaces", "repaired", "gallons", "confuse", "radiates", "banned", "november",
            "bills!", "entire", "attached", "mastic", "flex", "moist", "hail", "battens", "counterbattens",
            "summertime", "bleeding", "crawlspace", "mistake", "neighborhood", "extruded", "(xps)", "grade", "vent",
            "gas-fired", "helped", "double-pane", "windowsill", "rained", "low-emissivity", "hotter", "single-pane",
            "#2", "cm", "inches)", "#3", "renovating", "placing", "faces", "#5", "escapes", "styles", "leaking",
            "rigid", "1c", "programmable", "dirt", "homeowners", "follow", "virtually", "strips", "tank's",
            "indicated", "apartments", "detached", "(called", "raised", "transferred", "transfers", "krypton",
            "casing", "blinds", "mid-efficiency", "80", "900mm", "regard", "drawings", "moniker", "colored", "titled",
            "blends", "decidedly", "adobe", "insulation)", "density", "bridging", "fibres", "borates", "potato",
            "starch", "favoured", "warmcell", "chips", "resins", "pavatex", "fully", "protects", "derive",
            "projectzero", "want", "automobile", "one-quarter", "fortunately", "age", "wallet!", "287", "(195)",
            "old-fashioned", "(37)", "(49)", "79", "trimming", "(12)", "freecycle", "area's", "lists", "starting?",
            "brill", "199", "(22)", "implement", "pitched", "sloped", "rolled", "enhancing", "prepared", "timescale",
            "bullivant", "interdisciplinary", "guzman", "volume", "workings", "annually", "purify", "intensified",
            "reports", "depend", "trace", "breaking", "depleted", "reaction", "osmosis", "importing", "birthday",
            "career", "manville", "underside", "oriented", "strand", "dimensional", "lumber", "i-joist", "fans",
            "quieter", "more-sophisticated", "stand", "laboratory", "forgot", "venting", "recognized",
            "supply-and-return", "vented", "chlorofluorocarbon", "racking", "pentane", "(ir)", "photo",
            "highest-r-value", "closed-cell", "polyester", "ain't", "stapling", "touted", "kraft", "hed", "65f",
            "thoughthe", "extended", "photograph", "(icfs)", "offered", "low-expansion", "wires", "glad", "slowly",
            "ic", "art", "airtight", "ic-rated", "color", "odd", "outputs", "dimmable", "replacement", "93%",
            "more-reliable", "sealed-", "okay", "outlets", "85f", "90f", "condensing-type", "wood-burning", "opaque",
            "aluminum-framed", "flowing", "flowed", "climate?", "metal-clad", "noticed", "blows", "doneprovide",
            "manvilles", "resides", "32", "r-20", "losing", "heat!", "finished", "plug", "leakiest", "factory", "snug",
            "cardboard", "tubes", "nozzle", "tube", "gun", "dries", "sealant", "crack", "opening", "#6", "21c",
            "(70f)", "#7", "3c", "comforter", "bring", "eight-hour", "#8", "unheated", "feet)", "ducting", "joined",
            "furnace's", "(many", "water-based", "merits", "slow-drying", "mix", "maximum", "segregate", "discharge",
            "fines", "positioned", "velac", "sneak", "consuming", "unpractical?", "danish", "retail", "energy-free",
            "slate", "18%", "throw", "immediately", "1998", "38", "7f", "draw", "(wattage)", "setups", "setting)",
            "55f", "cmhc", "poorly", "dismantled", "treatment", "too!", "(144", "ephemeral", "savannah", "palm",
            "countryside", "heather", "reed)", "pieces", "sawn", "prohibit", "contradistinction", "taps", "satisfying",
            "maybe", "factoring", "semi-detached", "triplexes", "condominiums", "upgraded", "accurate", "windows?",
            "permanent", "solve", "convection", "currents", "latch", "drapes", "leaks?", "stripping)", "difference?",
            "profile?", "decreases", "provincial", "furnaces)", "intrepid", "warranty", "neighbourhoods",
            "incineration", "emr", "stone-clad", "on-site", "adhering", "laws", "locator", "incorporating", "pounds)",
            "thrown", "count", "credentials", "tradition", "sparked", "cobtun", "worcestershire", "shoestring", "500!",
            "flint", "shovelled", "stamped", "trod", "mm)", "fortnight", "plumb", "rose", "others)", "consistency",
            "dough", "labour-intensive", "thoroughly", "laying", "meaning", "two-storey", "trench", "days)", "u-value",
            "exceeds", "poverty-in", "googlegoogle", "photovoltaic", "centimetre", "bouncing", "radiator", "excuse",
            "37", "35kg", "split?", "tub"});
    protected static final List<String> TOPIC8_TOPWORDS = Arrays.asList(new String[]{"*", "green", "construction",
            "environmental", "pollution", "design", "roofs", "uk", "living", "important", "local", "high", "site",
            "range", "environmentally", "friendly", "resources", "soil", "equipment", "like", "eco", "c60", "levels",
            "benefits", "increasing", "plants", "o", "government", "support", "area", "including", "non-toxic",
            "health", "sites", "areas", "issues", "chemicals", "growing", "regulations", "houses", "provide", "office",
            "community", "prevent", "harmful", "ecological", "reduction", "eco-friendly", "noise", "content",
            "structure", "techniques", "wide", "led", "neighbourhood", "thousands", "providing", "transport",
            "innovative", "maintenance", "likely", "university", "working", "land", "ventilation", "control",
            "according", "toxic", "scale", "clean", "protect", "address", "increasingly", "contribute", "cover",
            "lake", "pigments", "aim", "neighbours", "cooling", "europe", "spaces", "wish", "plan", "technology",
            "governments", "dust", "whilst", "prepare", "incorporate", "healthy", "germany", "medium", "popular",
            "extensive", "minimise", "awareness", "integrated", "skills", "practices", "research", "latest",
            "wildlife", "suitable", "aggregates", "benefit", "rainwater", "lack", "extraction", "particularly",
            "substances", "organisations", "bristol", "council", "section", "rises", "purpose", "tool", "reused",
            "components", "oils", "hazardous", "situation", "putting", "cheap", "movement", "drainage", "layers",
            "(to", "encourage", "urban", "nottingham", "aspects", "affordable", "run-off", "particulate", "centres",
            "limited", "lifestyle", "possibly", "particular", "underfloor", "mission", "offers", "laka", "fibre",
            "love", "carrier", "preservatives", "respiratory", "asthma", "consumers", "knowledge", "excess", "native",
            "filter", "shop", "training", "members", "vegetation", "deep", "ongoing", "flat", "construct", "species",
            "sedum", "sound", "fixed", "bear", "response", "remaining", "concern", "flexibility", "stoneguard",
            "cooking", "white", "principles", "maximise", "cars", "filters", "cultural", "replicated", "john", "pm10",
            "risks", "waterways", "alternatively", "collect", "tools", "kids", "re-used", "nearby", "contributing",
            "usage", "organisation", "negative", "asbestos", "appearance", "trading", "covered", "shetland", "email",
            "there's", "pilot", "residents", "i'd", "assignment", "class", "included", "far", "useable", "soon",
            "complete", "beautiful", "expanded", "porous", "together)", "voc-free", "cans", "blue", "vegetable",
            "damp", "sod", "exciting", "named", "solutions", "policies", "planted", "methodology", "weight-loading",
            "diversity", "irrigation", "balconies", "maintain", "pitch", "carefully", "root", "water)", "substrate",
            "crushed", "spreading", "commonly", "directly", "grow", "toxins", "likelihood", "biodiversity",
            "aesthetic", "opportunities", "uk's", "70%", "ideas", "looking", "2016", "collaboration", "workforce",
            "sets", "demonstrating", "link", "agency", "identify", "fixtures", "clearing", "caps", "studied", "apart",
            "metals", "horticultural", "fine", "lesson", "4%", "pollute", "distances", "penetrate", "silicates",
            "cleaners", "erosion", "groundwater", "disturbance", "stress", "piles", "locate", "sulphur", "handling",
            "conform", "damaging", "effort", "pay", "aware", "tyres", "utilise", "interesting", "insurance",
            "baseline", "householders", "looks", "air-borne", "cleaner", "declining", "sadly", "scotframe", "offices",
            "we've", "england", "developments", "experience", "integration", "weed", "downstairs", "month", "i'm",
            "isn't", "indicative", "followed", "poster!", "optimizing", "soaks", "tones", "isonat", "absorbent",
            "(holds", "cadmium", "stabilisers", "thickeners", "(carbon", "disease", "dizziness", "liver", "varieties",
            "fulfilled", "accordance", "respective", "greenguard", "(voc", "antique", "extender", "trees)", "citrus",
            "(d-limonene)", "allergy", "american", "(810", "clothesline", "smarter", "boxes", "bestseller",
            "oxygenics", "dairy", "adult", "coke", "enterprising", "connects", "foster", "initiatives", "engagement",
            "partnership", "professionals", "gardens", "babylon", "extensions", "repellent", "escaping)", "life)",
            "seeds", "draining", "drought-tolerant", "nutrient", "perennials", "wildflowers", "succulents", "mats",
            "commercially", "bees", "beetles", "filtering", "retaining", "evaporates", "preserving", "appeal",
            "sheets", "widespread", "10-15%", "hindered", "uptake", "agenda", "planners", "dull", "testing",
            "sustainable/", "acoustics", "eon", "accounts", "25%", "teaching", "gillott", "professor", "fast-track",
            "wastage", "shading", "utilisation", "bathrooms)", "regarded", "stack", "unequivocal", "summarizing",
            "auditor", "landscaping", "originate", "intensifying", "(78", "95%)", "reflects", "fundamental",
            "britain's", "94", "sculpted", "raised-bed", "proposing", "herbs", "r-19", "r-15", "afford", "this)",
            "coatings", "brickwork", "tough", "cactus", "described", "rediscovered", "incidents", "(typically",
            "microns", "invisible", "naked", "deeply", "sulphates", "inhalation", "monoxide", "glues", "woods",
            "cleared", "silt", "turbid", "restricts", "filtration", "aquatic", "poison", "soak", "contaminated",
            "treat", "shouting", "radios", "loud", "distracting", "blood", "disturb", "cycles", "habitat", "mesh",
            "screening", "skips", "inspect", "washed", "spills", "contamination", "wastewater", "catalytic", "careful",
            "quiet", "shields", "slack", "perceived", "enforcement", "irreversibly", "reputation", "parents",
            "understandings", "grid", "katherine", "$800", "works", "additionally", "hofmeister", "beam",
            "mantelpiece", "waste)", "95%", "yards", "sourcing", "standby", "subscribed", "well-being",
            "construction?", "physical", "contrary", "fire-resistant", "instructions", "semi-permanent", "tents",
            "asia", "exploring", "estates", "findhorn", "forres", "governmental", "(ngo's)", "eco-building", "designs",
            "constructions", "balanced", "earths", "480", "fronds", "sorts", "(actually", "rounded", "basically",
            "bundle", "wedge", "rough", "disadvantage", "nailed", "spaced", "cleaned", "diminished", "human-driven",
            "deserve", "one's", "influences", "yoghurt", "progress", "advances", "transfer", "booklet", "cities",
            "health-related", "pesticides", "electro-magnetic", "proximity", "trails", "sporting", "facilities",
            "parks", "vs", "outweighs", "practise", "walling", "notoriously", "constructing", "fascia", "comparing",
            "vehicle)", "removable", "identification", "consult", "fueling", "challenges", "inevitability", "moulds",
            "strengthen", "integrating", "non-polluting", "practises", "headquarters", "(still", "chandlery", "prior",
            "hurricane", "occurence", "hastened", "scandinavia", "inverurie", "discounted", "eternally", "imaging",
            "issued", "practicalities", "'greenhouse", "yorkshire", "flights", "fastest-growing", "plymouth", "fellow",
            "mansion", "semi", "pioneers", "1980s", "low-energy", "bridges'", "eliminating", "worldwide)",
            "production/transportation", "laptop", "wireless", "commute", "congestion", "drive-alone", "doe's",
            "1800s", "fork", "ladle", "averaging", "individually", "300-500mm", "200mm", "gravel", "hardens",
            "scepticism", "geological", "compromising", "erect", "viable", "scottish", "holistic", "partnerships",
            "completion", "january", "re-fuel", "cell", "addressing", "'green'", "sanjida", "del", "uponstumble",
            "yahoobuzzyahoobuzz", "bebobebo", "mindsindependent", "print", "normal", "acknowledged", "successfully",
            "interviewing", "piece", "ostracised", "begun?", "new-build", "floating", "stainless", "clad", "rattling",
            "loughborough", "baths", "sparkly", "disco", "buff", "trail", "waif", "begging", "nightmare", "haven",
            "(that's", "upside)", "chill", "everyone's", "community-minded", "childhood", "hiding", "leylandii",
            "upset", "berated", "easyjet", "tuscany", "allotment", "double-glazing", "a+", "a/a+", "aircraft)"});
    protected static final List<String> TOPIC9_TOPWORDS = Arrays.asList(new String[]{"temperature", "house",
            "consumption", "time", "summer", "thermostat", "days", "set", "day", "houses", "setback", "floor",
            "temperatures", "savings", "times", "surface", "winter", "different", "night", "humidity", "electrical",
            "radiation", "problems", "lower", "heating", "condensation", "furnace", "ground", "results", "means",
            "cloudy", "levels", "measured", "really", "place", "fan", "data", "sunny", "solar", "setting", "outdoor",
            "window", "setforward", "higher", "indoor", "save", "cooling", "south", "8", "test", "point", "facing",
            "recovery", "longer", "did", "similar", "occupants", "strategy", "rest", "lead", "hours", "reference",
            "mixed", "second", "differences", "surrounding", "completely", "expected", "mean", "figure", "season",
            "64f", "reduced", "presentation", "poster", "units", "calculated", "early", "square", "difference",
            "study", "chosen", "unless", "daytime", "reason", "energy-saving", "a/c", "twin", "ccht", "trials",
            "determine", "examined", "experiments", "form", "motors", "daily", "30%", "degrees", "vertical", "groups",
            "canada", "(see", "61f", "five-minute", "measurements", "rh", "experiment", "trends", "final", "reached",
            "north", "mechanical", "overall", "saved", "13%", "technology", "speed", "located", "moment", "comfort",
            "2)", "increased", "collection", "wanted", "p", "argon-filled", "recommended", "minutes", "energy?",
            "(18c)", "collected", "intervals", "das", "understand", "drywall", "thermocouple", "threshold", "removed",
            "kept", "elements", "meter", "popularity", "coldest", "conditioner", "shorter", "resulting", "nearly",
            "predicted", "town", "1)", "primarily", "weather", "distinct", "separate", "result", "care", "tightly",
            "compare", "quarter", "seasons", "peak", "ran", "settings", "benchmark", "72f", "(16c)", "circulation",
            "recorded", "hourly", "pyronometer", "arbitrarily", "respectively", "choosing", "skylights", "ton",
            "learning", "texts", "maps", "content", "determined", "black", "box", "oven", "performs", "unfortunately",
            "despite", "2%", "(but", "entirely", "birds", "noted", "improvement", "2003", "decision", "3)", "ice",
            "relative", "50%", "introduction", "greenhouses", "plates", "mold", "framing", "corners", "short)", "(12",
            "closed", "uncomfortable", "remained", "employing", "topic", "strategies", "temperature)", "workday",
            "facility", "r-2000", "meters", "pulse", "monitored", "measuring", "hottest", "thermocouples", "locations",
            "dew", "7c)", "determining", "(mj/m2)", "divide", "(20c)", "(sunny", "perfectly", "benchmarking",
            "resulted", "partly", "on-times", "applying", "21%", "characteristics", "expect", "slightly", "90",
            "consensus", "lift", "highlight", "images", "(2)", "browsed", "(4)", "(5)", "depicting", "brief",
            "description", "colourful", "complement", "chairs", "resisting", "purchases", "peeling", "august", "till",
            "2008-12", "precipitates", "(140f", "garage", "lunch", "bookstore", "processing", "stuffed", "nuisance",
            "sunlawn", "201", "multiple", "cookers", "interior", "banded", "al", "court", "regulate", "underway",
            "scysim", "acts", "detrimental", "ozone-destroying", "(20", "038%)", "wavelength", "amounted", "ranching",
            "agents", "freon", "marked", "draft", "lettuce", "import", "energy-conserving", "starting", "(my", "5/8",
            "formaldehyde-free", "perm", "father-in-law", "reliability", "45f", "find?", "protected", "flashings", "b",
            "hotter", "loose-blown", "vinyl", "inefficiency", "(sealant)", "oxides", "continually", "spillages",
            "harness", "realistic", "resales", "rolls-royce", "re-sized", "fittings", "setbacksdo", "marianne",
            "armstrong", "adjusting", "(reducing", "aid", "employed", "(increasing", "canadian", "(ccht)", "identical",
            "two-story", "ottawa", "20)", "20022003", "series", "housesone", "houseto", "examine", "(22c)",
            "performed", "(das)", "indicating", "(heating", "mode)", "on-time", "transient", "intervals10", "seconds",
            "(basement", "consecutive", "second-floor", "tracked", "hallway", "condense", "(3", "drops", "ambient",
            "ice)", "bedroom", "calculations", "resolution", "relationship", "correlation", "reset", "(rh)", "10%)",
            "humidifiers", "tipping", "(grams", "kilogram", "air)", "ratiosfor", "floorwere", "averaged", "sensor",
            "incident", "wall-mounted", "differentiate", "tracks", "41f", "(5c)", "thresholds", "labeled", "cloudy)",
            "belonging", "essence", "distinguish", "resultant", "scatter", "plotted", "static-pressure", "ductwork",
            "loads", "inherent", "furthermore", "negligible", "adjustments", "demonstrated", "tables", "decreased",
            "(expressed", "percentage)", "17%", "projecting", "seasonal", "setbacks", "nighttime", "evening",
            "anticipated", "ample", "reheat", "(17", "8c)", "(it", "center", "55%", "mortgage", "corporation",
            "suggests", "14f", "(-10c)", "excesses", "stains", "ceilings", "structural", "allergic", "fluctuate",
            "breath", "perspiration", "bathing", "problematic", "27f", "(-2", "19%not", "table", "sunniest",
            "totaling", "kwh", "timeup", "daysthe", "evenings", "proved", "consistently", "expectedfurnace", "23%",
            "drawback", "pulped", "example)", "edinburgh", "off-cuts", "educational", "non-governmental", "combed",
            "butts", "lengths", "appealing", "signing", "inform", "(burns)", "off", "screwdriver", "(4",
            "transferring", "78", "exits", "$3800", "promises", "ultimate", "objective", "filling", "minimising",
            "chronic", "prosperous", "urgency", "codes", "drilled", "'zero", "sandison", "brownfield", "struck",
            "battery/fuel", "comforts", "non-domestic", "university's", "'as", "liveable", "unsurprisingly", "loaves",
            "taper", "plinth", "driveways", "admit", "non-cement", "pioneering", "mixxmixx", "lawrence", "worried",
            "roof)", "places)", "couple", "returned", "person!", "answering", "sailing"});

    public AbstractGibbsSamplerTestFixture() {
        super();
    }

}
